version: '3'
services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      #- ./node_modules:/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./dbBackup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file: .env
